export const actionNames = {
    ADD_NEW_BOT: "ADD_NEW_BOT", 
    SET_GRID_AXIS: "SET_GRID_AXIS",
    SET_BOT_VALUE: "SET_BOT_VALUE",
    SET_ROUTE: "SET_ROUTE",
    CONTROL_ROVER: "CONTROL_ROVER",
    RESET_ROVERS: "RESET_ROVERS",
} 