export const actionNames = {
    SET_GRID_AXIS: "SET_GRID_AXIS",
    SET_CURRENT_POSITION: "SET_CURRENT_POSITION",
    SET_ROUTE: "SET_ROUTE",
    CONTROL_ROVER: "CONTROL_ROVER",
    RESET_ROVERS: "RESET_ROVERS",
    UPDATE_CURRENT_POSITION: "UPDATE_CURRENT_POSITION"
} 